### ISSUE TITLE
Spacing revision

### ISSUE THREAD

**Issue by draysonandstock** [Financial-Times/o-subs-card#5]
Hi, 
Please can we remove some of the extra padding above 'Other Subscription options:' text. This is only at the smaller breakpoints as shown and should match the spacing of the largest breakpoints currently. Thanks

<img width="961" alt="example" src="https://user-images.githubusercontent.com/11214093/30209000-c9cdeb62-948d-11e7-97e6-d9a3c63e74b6.png">

<img width="1240" alt="ideal current at largest breakpoint" src="https://user-images.githubusercontent.com/11214093/30209044-f0a48a3e-948d-11e7-8cf3-f479ed015a31.png">

**Comment by gvonkoss** [comment]
This isn't Origami remit, and James has confirmed that.
